version: '3'

services:
  bookstore-api:
    container_name: bookstore-api
    build: ./app
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - bookstore-db
    volumes:
      - ./app:/code/app
    environment:
      DB_HOST: localhost
      DB_PORT: '5432'
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: test

  bookstore-db:
    container_name: bookstore-db
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '5432:5432'
    volumes:
      - ${PWD}:/var/lib/postgresql/data

volumes:
  bookstore-db:
